/**
    Namespace for LZW compression and decompression.
    Methods:
        LZW.compress(uncompressed)
        LZW.decompress(compressed)
*/
export default class LZW {
  /**
    Perform the LZW compression
    uncompressed - String. The string on which to perform the compression.
    */
  static compress(uncompressed: string) {
    // Initialize dictionary
    let dictionary: { [index: string]: number } = {};
    for (let i = 0; i < 256; i++) {
      dictionary[String.fromCharCode(i)] = i;
    }

    let word = "";
    let result = [];
    let dictSize = 256;

    for (let i = 0, len = uncompressed.length; i < len; i++) {
      let curChar = uncompressed[i];
      let joinedWord = word + curChar;

      // Do not use dictionary[joinedWord] because javascript objects
      // will return values for myObject['toString']
      if (dictionary.hasOwnProperty(joinedWord)) {
        word = joinedWord;
      } else {
        result.push(dictionary[word]);
        // Add wc to the dictionary.
        dictionary[joinedWord] = dictSize++;
        word = curChar;
      }
    }

    if (word !== "") {
      result.push(dictionary[word]);
    }

    let resultString = "";
    result.forEach((charIndex: number) => {
        resultString += String.fromCharCode(charIndex + LZW.CHAR_OFFSET);
    });
    
    return resultString;
  }

  static CHAR_OFFSET: number = 16;
  /**
        Decompress LZW array generated by LZW.compress()
        compressed - Array. The array that holds LZW compressed data.
    */
  static decompress(compressedDatas: string): string {
    const compressed: number[] = [];
    for( let i = 0; i < compressedDatas.length; i++){
        compressed.push(compressedDatas.charCodeAt(i) - LZW.CHAR_OFFSET);
    }

    // Initialize Dictionary (inverse of compress)
    let dictionary: { [index: number]: string } = {};
    for (let i = 0; i < 256; i++) {
      dictionary[i] = String.fromCharCode(i);
    }

    let word = String.fromCharCode(compressed[0]);
    let result = word;
    let entry = "";
    let dictSize = 256;

    for (let i = 1, len = compressed.length; i < len; i++) {
      let curNumber = compressed[i];

      if (dictionary[curNumber] !== undefined) {
        entry = dictionary[curNumber];
      } else {
        if (curNumber === dictSize) {
          entry = word + word[0];
        } else {
          return "";
        }
      }

      result += entry;

      // Add word + entry[0] to dictionary
      dictionary[dictSize++] = word + entry[0];

      word = entry;
    }

    return result;
  }
}
